######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 9 16:35:08 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Brute.h Fast.h Point.h PointPlotter.h
SOURCES += Brute.cpp Fast.cpp main.cpp Point.cpp PointPlotter.cpp
